audit_header: false
title: Treasure Davis Real Estate Video Blog
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Treasure Davis Team - your professional Colorado Springs Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Our Listings
    url: 'http://www.treasuredavis.com/results/?UserID=all'
client:
  name: Treasure Davis
  license_number:
  about_markdown: >
    Treasure Davis is the consummate real estate professional in Colorado
    Springs, Fountain, Monument and Woodland Park, Colorado. Treasure Davis is
    committed to providing first-class service by delivering effective strategies
    that achieve the best results for each client. Her strong drive to succeed
    for her clients is matched by her equally strong sense of integrity.



    Treasure Davis is proud to be a Volunteer Realtor on Ft. Carson. Assisting
    our military is gives her pride in giving back to people that give so much
    every day! Treasure Davis, Realtor in Colorado Springs is proud to offer her
    MilitaryFirst program to all active duty and retired military members.
  market: Colorado Springs
  brand: The Treasure Davis Team
  brokerage: 'RE/MAX Properties, Inc.'
  address: '1740 Chapel Hills Dr.<br>Colorado Springs, CO 80920'
  phone: (719) 354-7746
  email: homes@treasuredavis.com
  url: 'http://www.treasuredavis.com'
  first_CTA_text: Home Evaluation
  first_CTA_URL: 'http://www.treasuredavis.com/sell/'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.treasuredavis.com/buy/'
  VR_form: 'http://oi.vresp.com?fid=17b8cb16c6'
welcome_headline: Get Educated About Real Estate
welcome_text_markdown: 'Our mission at The Treasure Davis Team is to be your best resource for real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.'
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/ColoradoSpringsHouseValues/'
  linkedin_url: 'https://www.linkedin.com/in/coloradospringshomes'
  gplus_url: 'https://plus.google.com/u/0/+TreasureDavis'
  youtube_url: 'https://www.youtube.com/user/treasuredavis1'
  twitter_url: 'https://twitter.com/teamdavis1004'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/TreasureDavis/'
  trulia_url: 'https://www.trulia.com/profile/treasure-davis-agent-colorado-springs-co-zg6v559n/overview'
  yelp_url: 'https://www.yelp.com/biz/treasure-davis-re-max-properties-colorado-springs'
  podcast_url:
podcast:
  title: The Treasure Davis Team Real Estate Podcast
  categories: News & Politics
  image:
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Colorado Springs Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Treasure Davis Team - your professional Colorado Springs Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: Treasure Davis
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_text: Real Estate Video Blog
  hero_background_hex: '#730709'
  hero_image_path: /img/background.jpg
brand_color: '#730709'
theme_color: '#730709'
theme_text_color: '#353535'
main_body_color: '#f9f9f9'
main_body_text_color: '#353535'